version: "3.8"

services:
  order-db:
    image: mysql:8.0
    container_name: order-db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_HOST=%
    ports:
      - '3307:3306'
    volumes:
      - ./order/db:/docker-entrypoint-initdb.d

  restaurant-db:
    image: mysql:8.0
    container_name: restaurant-db
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=restaurant
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    volumes:
      - ./restaurant/db:/docker-entrypoint-initdb.d
